name: C/C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  hello-there:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install cppunit
    run: echo hello world
