name: C/C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: C++ linter
      uses: actions/checkout@v2
      uses: cpp-linter/cpp-linter-action@v2
      id: linter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        style: file
    - name: checkout
      uses: actions/checkout@v2
    - name: install cppunit
      run: sudo apt install -y libcppunit-dev
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make test
      run: make test
